function [genNoise] = cwgn(mean, var, dim1, dim2 )
    genNoise = complex( ...
                        mean + (sqrt(var).*randn(dim1,dim2)),...
                        mean + (sqrt(var).*randn(dim1,dim2)) );
end
